networks:
  nginx_network_external:
    name: nginx_network_external
    external: true
    #attachable: true
services:
  nginx:
    build: .
    container_name: nginx
    image: nginx
    ports:
      - "444:443"
      - "81:80"
    restart: always
    networks:
      - nginx_network_external
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro